// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrqzcmoqxxdmtfxutcjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndycXpjbW9xeHhkbXRmeHV0Y2pqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzOTM1NzksImV4cCI6MjA3OTk2OTU3OX0.8GaZQkAu5tMZJ3Ej2i0bo7QEQuswXnD0oe0qjqqQT7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});